services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=url_shortener
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
#    ports:
#      - "5432:5432" # ino avaz kon bezar roy 127.0.0.1
    networks:
      - db_access

  web:
    build: .
    command: >
      sh -c "alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - db_access
      - public

    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  db_access:
    external: true
    name: db_access
  public:
    external: true
    name: public
